Fatal error: exception Failure("duplicate local a")